@{
    ModuleVersion = '2204.19.1'
    GUID = 'd8dcfccc-7a12-4dfd-a27a-c647b408e1bf'
    Author = 'Julian Easterling'
    PowerShellVersion = '3.0'
    RootModule = 'Networking.psm1'
    NestedModules = @(
        "BindTools.psm1"
        "IPerf.psm1"
        "NMap.psm1"
        "PacketCapture.psm1"
        "Wireless.psm1"
        "WirelessProfile.psm1"
        "Wireshark.psm1"
    )
    TypesToProcess = @()
    FormatsToProcess = @()
    FunctionsToExport = @(
        "Add-PacketFilter"
        "Clear-PacketFilter"
        "Connect-WirelessProfile"
        "Convert-PacketCaptureFile"
        "Disconnect-Wireless"
        "Export-WirelessProfile"
        "Find-Nmap"
        "Find-WirelessAccessPoint"
        "Get-IPv4NetworkClass"
        "Get-IPv4NetworkEndAddress"
        "Get-IPv4NetworkStartAddress"
        "Get-IPv4Subnet"
        "Get-NetworkEstablishedConnection"
        "Get-NetworkInterface"
        "Get-NetworkIP"
        "Get-NetworkListeningPorts"
        "Get-PacketFilter"
        "Get-PrimaryIP"
        "Get-PrimaryMask"
        "Get-PrimarySubnet"
        "Get-PublicIP"
        "Get-TSharkInterfaces"
        "Get-WirelessProfile"
        "Get-WirelessState"
        "Import-WirelessProfile"
        "Invoke-ArpaName"
        "Invoke-Dig"
        "Invoke-Host"
        "Invoke-IPerf"
        "Invoke-IPerfServer"
        "Invoke-IPerfClient"
        "Invoke-Http"
        "Invoke-Nmap"
        "Invoke-NSLookup"
        "Invoke-NSUpdate"
        "Invoke-PingScanNetwork"
        "Invoke-ScanHost"
        "Invoke-ScanHostPort"
        "Invoke-ScanLocalNetwork"
        "Invoke-ScanNetwork"
        "Invoke-TShark"
        "Invoke-TSharkCapture"
        "New-FirewallRule"
        "New-UrlReservation"
        "New-WirelessProfile"
        "Ping-Host"
        "Remove-FirewallRule"
        "Remove-UrlReservation"
        "Remove-WirelessProfile"
        "Search-Network"
        "Show-UrlReservation"
        "Show-WirelessInterface"
        "Start-PacketCapture"
        "Stop-PacketCapture"
        "Test-PrivateIPv4"
        "Test-Url"
    )
    AliasesToExport = @(
        "arpaname"
        "bind-arpaname"
        "bind-dig"
        "bind-host"
        "bind-nslookup"
        "bind-nsupdate"
        "dig"
        "host"
        "iperf"
        "iperf-server"
        "iperf-client"
        "ipv4-start"
        "ipv4-end"
        "ipv4-subnet"
        "nmap"
        "nmap-host"
        "nmap-port"
        "nmap-scan"
        "scan-network"
        "nslookup"
        "nsupdate"
        "tshark"
        "tshark-showinterfaces"
        "tshark-capture"
    )
}
