@{
    ModuleVersion = '2112.25.1'
    GUID = '907bef0d-cf0d-47de-a77b-282e48ce85b1'
    Author = 'Julian Easterling'
    PowerShellVersion = '3.0'
    RootModule = 'Ansible.psm1'
    NestedModules = @(
      "AnsibleDev.psm1"
      "AnsibleInventory.psm1"
      "AnsibleLint.psm1"
      "AnsiblePlaybook.psm1"
    )
    TypesToProcess = @()
    FormatsToProcess = @()
    FunctionsToExport = @(
      "Assert-AnsibleProvision"
      "Confirm-AnsiblePlaybookSyntax"
      "Get-AnsibleConfig"
      "Get-AnsibleConfigDump"
      "Get-AnsibleConfigFile"
      "Get-AnsibleInventoryGraph"
      "Get-AnsibleInventoryAsJson"
      "Get-AnsibleInventoryAsToml"
      "Get-AnsibleInventoryAsYaml"
      "Get-AnsibleLintRules"
      "Get-AnsibleLintTags"
      "Get-AnsiblePlaybookHosts"
      "Get-AnsiblePlaybookTags"
      "Get-AnsiblePlaybookTasks"
      "Invoke-Ansible"
      "Invoke-AnsibleConfig"
      "Invoke-AnsibleContainer"
      "Invoke-AnsibleDoc"
      "Invoke-AnsibleGalaxy"
      "Invoke-AnsibleHostCommand"
      "Invoke-AnsibleInventory"
      "Invoke-AnsibleLint"
      "Invoke-AnsibleLintPlaybook"
      "Invoke-AnsibleLintRole"
      "Invoke-AnsiblePlayBase"
      "Invoke-AnsiblePlaybook"
      "Invoke-AnsiblePlayDev"
      "Invoke-AnsiblePlayTest"
      "Invoke-AnsibleProvision"
      "Invoke-AnsibleVault"
      "Ping-AnsibleHost"
      "Protect-AnsibleVariable"
      "Reset-AnsibleEnvironmentDev"
      "Reset-AnsibleEnvironmentTest"
      "Show-AnsibleFacts"
      "Show-AnsibleVariables"
      "Test-AnsiblePlaybookSyntax"
      "Test-AnsibleProvision"
      "Update-AnsibleHost"
      "Update-AnsibleProvision"
    )
    AliasesToExport = @(
      "ansible"
      "ansible-config"
      "ansible-container"
      "ansible-dev-reset"
      "ansible-dev-play"
      "ansible-doc"
      "ansible-encrypt"
      "ansible-facts"
      "ansible-galaxy"
      "ansible-hosts-exec"
      "ansible-hosts-ping"
      "ansible-hosts-update"
      "ansible-inventory"
      "ansible-lint"
      "ansible-lint-playbook"
      "ansible-lint-role"
      "ansible-playbook"
      "ansible-playbook-hosts"
      "ansible-playbook-syntaxcheck"
      "ansible-playbook-tags"
      "ansible-playbook-tasks"
      "ansible-playbook-test"
      "ansible-play-base"
      "ansible-play-dev"
      "ansible-play-test"
      "ansible-provision-check"
      "ansible-provision-server"
      "ansible-provision-test"
      "ansible-provision-update"
      "ansible-reset-dev"
      "ansible-reset-test"
      "ansible-test-play"
      "ansible-test-reset"
      "ansible-variables"
      "ansible-vars"
      "ansible-vault"
      "Check-AnsiblePlaybookSyntax"
      "Validate-AnsiblePlaybookSyntax"
      "ping-hosts.sh"
      "play-base.sh"
      "play-dev.sh"
      "provision-check.sh"
      "provision-server.sh"
      "provision-test.sh"
      "provision-update.sh"
      "reset-dev.sh"
      "reset-test.sh"
      "update-servers.sh"
    )
}
