name: Create and publish my modules packages

on:
  push:
    paths:
      - modules/**

  pull_request:
    types: [opened, reopened]
    paths:
      - modules/**

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Create packages
        run: ./choco/build.ps1

      - name: Publish packages
        if: startsWith(github.ref, 'refs/heads/main')
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
        run: >
          dotnet nuget push **/*.nupkg
          --api-key '${{ secrets.NUGET_API_KEY }}'
          --source '${{ vars.NUGET_URL }}'
          --skip-duplicate
