name: Create and publish my packages

on:
  push:
    paths:
      - 'choco/dcjulian29.psmodules/**'
      - 'Modules/**'

  pull_request:
    types: [opened, reopened]
    paths:
      - 'choco/dcjulian29.psmodules/**'
      - 'modules/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.1

      - name: Create individual module packages
        run: ./choco/build.ps1

      - name: Create chocolatey package
        run: ./choco/dcjulian29.psmodules/build.ps1

      - name: Publish module packages
        if: startsWith(github.ref, 'refs/heads/main')
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
        run: >
          Set-Location ${{ github.workspace }}\.packages;
          dotnet nuget push **/*.nupkg
          --api-key '${{ secrets.NUGET_API_KEY }}'
          --source '${{ vars.NUGET_URL }}'
          --skip-duplicate

      - name: Publish chocolatey package
        if: startsWith(github.ref, 'refs/heads/main')
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
        run: >
          Set-Location ${{ github.workspace }}\.meta;
          dotnet nuget push **/*.nupkg
          --api-key '${{ secrets.NUGET_API_KEY }}'
          --source '${{ vars.CHOCO_URL }}'
          --skip-duplicate
