name: Create and publish profile packages

on:
  push:
    paths:
      - 'bin/**'
      - 'choco/dcjulian29.pshell.profile\**'
      - 'choco/dcjulian29.pwsh.profile\**'
      - Microsoft.PowerShell_profile.ps1
      - Microsoft.VSCode_profile.ps1
      - Profile.ps1

  pull_request:
    types: [opened, reopened]
    paths:
      - 'bin/**'
      - 'choco/dcjulian29.pshell.profile/**'
      - 'choco/dcjulian29.pwsh.profile/**'
      - Microsoft.PowerShell_profile.ps1
      - Microsoft.VSCode_profile.ps1
      - Profile.ps1

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Create Powershell profile package
        run: ./choco/dcjulian29.pshell.profile/build.ps1

      - name: Create Powershell Core profile package
        run: ./choco/dcjulian29.pwsh.profile/build.ps1

      - name: Publish packages
        if: startsWith(github.ref, 'refs/heads/main')
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
        run: >
          dotnet nuget push .packages/*.nupkg
          --api-key '${{ secrets.NUGET_API_KEY }}'
          --source '${{ vars.NUGET_URL }}'
          --skip-duplicate
